language: haskell
ghc:
- 7.6
- 7.8
notifications:
  slack:
    secure: m+r87uwG+Yu5TzJqBCeCeBfpLSldJWAPwu1SR02lUEqhylxyVChtsur7Jea+6dBfQs7bHbaPH0CxSFoPx+EzMAM+/z5BRgBoYRDqCB+jRMauP5pkRVKAjw33nU3wkRmzY8gsBBwkbXahgG6W0PazXM+Mabg6ejJbJ5ClXdFz4id6D+ZBsx5Us2VqMWL9k2n3liEvzrp9qQnE++Qj1RFeHb52OUflOtF9RJvB0etRf8/Y2Tu+GQKfNsdXDkVrGXC9aGNlS097St7GiG44P2lZoxE2Vd0GWZXh+bDzNTgN8XdVu5wOfZ6vSCFhSRlG0hKg5uhc2xQXENuk0T67dCe9Jz9QCunGiHeb2oF1YmBZ3N25h06VR+y/emnlXo4VEpnhdC/ceiOPqzLUeCARtjTN3pmutaKDpCpCPCInGWtNwZMZ0Bht1IbXKbc83mcbMFuFVrAu/9oGDHmxpZuTdFQinoePgRvhf6o610uJDpmqBu156wXC/wDL+c8uAGV0Ks7ii3GQWuoAHA5hlGNrM0ZA/hHCFF/QKolNQaropxAUJz1vBZHFxOVQOmwb7XwuINrAl5Yu89NKYR6COAbIzJKnpbGgxqQMN09cEt5ApGMEvMf7ygTImJVMZeRTBpUMBkYseCTIlcMu+NarC8pS64AVAZdcuH5eEo4/RhmG99Q0jlw=
