flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- SHA-1.6.4.2
- StateVar-1.1.0.0
- aeson-0.9.0.1
- async-2.0.2
- attoparsec-0.13.0.0
- auto-0.4.3.0
- base-orphans-0.4.0
- base64-bytestring-1.0.0.1
- bimap-0.3.0
- blaze-builder-0.4.0.1
- case-insensitive-1.2.0.4
- cereal-0.4.1.1
- comonad-4.2.6
- contravariant-1.3.1.1
- distributive-0.4.4
- dlist-0.7.1.1
- entropy-0.3.7
- exceptions-0.8.0.2
- hashable-1.2.3.3
- lifted-base-0.2.3.6
- loop-0.2.0
- matrix-0.3.4.3
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- nats-1
- network-2.6.2.1
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- resourcet-1.1.5
- scientific-0.3.3.8
- semigroups-0.16.2.2
- stm-2.4.4
- stm-chans-3.0.0.4
- syb-0.5.1
- tagged-0.8.1
- text-1.2.1.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.10.12.3
- void-0.7
- websockets-0.9.5.0
resolver: ghc-7.10
